### ISSUE TITLE
Add batch actions

### ISSUE THREAD

**Issue by smarquespt** [bottiger/SoundWaves#13]
It would be nice if we could have batch actions for downloading podcasts.

In my case I usually only download podcasts once a week. If we had this option I could have an option to dowload, for instance:

1. Download last week
2. Download last month
3 Any other frequency you find useful.

**Comment by bottiger** [comment]
I am actually working on refactoring the download manager at the moment, since it has a lot of legacy. I expect to spend a few days on it.

This is not a feature I would ever use so please let me know if this implementation would work for you.

The Playlist already have a "Download all" menu which I would rename to "Bulk download", "Mass download" or something similar. I just fixed it in the master branch :)
The "Bulk download" would spawn a dialog where one can choose a timespan.

1. Today
2. This week
3. This month

Do we really need more than a month? 

I also imagine that the bulk download would only download episodes which matches the playlist filters. This would allow you to filter out some subscriptions you don't want to download.

I would also put the same "mass download" menu inside each subscription activity - only affecting that specific subscription of course.

PS: There is already a setting to limit the total size of the Download folder. This would of course still be in effect.

**Comment by smarquespt** [comment]
> Bulk download

Perfect

> Do we really need more than a month?

No. It´s fine

> I also imagine that the bulk download would only download episodes which matches the playlist filters. This would allow you to filter out some subscriptions you don't want to download.

> I would also put the same "mass download" menu inside each subscription activity - only affecting that specific subscription of course

yes, that´s perfect

**Comment by bottiger** [comment]
I have made in initial implementation. It works if you just have a playlist where the episodes are sorted by date. If you start sorting in reverse order or reorganizing them manually there are some undefined behavior, but I have to think about how to handle that.

In the meantime I'm getting ready for a new release whenever you have time to do the translation of the new strings.

**Comment by smarquespt** [comment]
@bottiger 

Updated on transifex. Can you fetch them there?

And this string:

"Download all episodes in the playlist form the" shouldn´t be: 

"... for the..."

**Comment by bottiger** [comment]
You are correct, it should be "for the".
