### ISSUE TITLE
How come 0.150 is the newest version on F-Droid?

### ISSUE THREAD

**Issue by e3b** [bottiger/SoundWaves#138]
Google Play Store has 0.157. Why? I'm just curious; don't want to be rude.

**Comment by bottiger** [comment]
@e3b It's not rude to ask. However, the reason is this. F-droid can a bit slow to update whenever I publish a new version. Therefore, if a new release contains one or more critical bugs it's a real bummer to have it published on F-droid since I have to wait several days before a fixed version is ready. Also, as far as I know F-droid does not support beta versions.

Therefore I first publish a beta version on Google play. If everything works great I will pulish it and push a release to F-droid as well. If there are bugs I publish a new beta version on Google Play.

Recently I have had several problems with a few components, and thus not been able to push a new version to F-droid.

That said, I just pushed 0.157 which should be available shortly.
