### ISSUE TITLE
Podcast subscription title with strange letters

### ISSUE THREAD

**Issue by smarquespt** [bottiger/SoundWaves#17]
For instance:

Mixórdia de temáticas (you can find it in gpodder) is MixÃ3rdia de temÃiticas

Pontapés na gramática (on gpodder also) is PontapÃs na gramÃitica

And so on..

All of these work fine in https://github.com/antennapod/AntennaPod

By the way, you may find useful some og antennapod code. Check it out.

**Comment by bottiger** [comment]
Good observation. I do not remember where the problem is but I will investigate it at some point in the near future.

**Comment by bottiger** [comment]
I may be wrong, but I'm afraid this have to wait.

As far as I can see the reason the letters are displayed as garbage is that the webpage is encoded in UTF-8 but the feed claims it's encoded in iso-8895-1. Firefox also seems to have reading problems of the character.

That said, while (I think) bug is their feed other app's seem to read the feed just fine. If they can do it so can I :) However, it requires quite a log of work and since it's not really a bug in SoundWaves I will have to postpone it a bit.

![encoding](https://cloud.githubusercontent.com/assets/489129/6879244/f6c9cf2e-d4ef-11e4-86cc-53b7ecd190a8.png)

**Comment by smarquespt** [comment]
@bottiger 

> I will have to postpone it a bit.

No problem.

**Comment by smarquespt** [comment]
This also happens in podcasts episode title

**Comment by smarquespt** [comment]
@bottiger 

This might already be fixed in latest release. I won´t close this issue untill you´re sure that it is fixed. If you test booth and everything is fine on your side, could you close it?

**Comment by smarquespt** [comment]
Fixed in latest release.
