### ISSUE TITLE
Fetch transifex translations before release

### ISSUE THREAD

**Issue by smarquespt** [bottiger/SoundWaves#25]
@bottiger 

Since transifex is working fine, please fetch translations before each release. As I´m working on tx, there´s no need to create pull requests every time.

**Comment by bottiger** [comment]
I have create a small build script which should ensure that I from now on always ship with the latest translation from transifex

**Comment by smarquespt** [comment]
Looks like You forget it for 0.88. ;-)

**Comment by bottiger** [comment]
Sort of, but not really :)
Now I actually don't remember the specific problem but tansifex had lost connection to github (maybe because of the ddos?) and hadn't refreshed for days. I wasn't sure if everything was synced up and if I was going to delete new strings by pulling and old copy from transfex. I also didn't want to push 0.88 any longer due to some bad crashes.

0.90 will bring an updated translation and peace on earth :)

**Comment by smarquespt** [comment]
> and peace on earth :)

Loved it
