### ISSUE TITLE
Option for subscription list view

### ISSUE THREAD

**Issue by willemw12** [bottiger/SoundWaves#34]
Minor feature request:
Have an option to display the subscriptions as a list (single column, in alphabetical order).

**Comment by bottiger** [comment]
Alphabetic sorting is a nobrainer, I'll be sure to include that in the next release.

Subscriptions as a list is also on the near/medium plan but requires some thinking. Let me ask you the usual question, why do you want it? Is it because you just like things in a list? Or do you want it to be more compact? Or something completely different?

It would be easy to just create a list, display a square thumbnail to the left and the podcast title to the right as all the other podcatchers to it. Maybe this is even the best solution.

However, before I start spending time on it I want to make sure I'm going to do it right. If you have any ideas, please let me know. And what type of information would you like to see - if any.

**Comment by willemw12** [comment]
Mainly, the feed title should be prominent. It is (for me) easier to scan through a list of text than a list/grid of icons. I may not (instantly) recognize the icon. Also, some feeds don't have an icon (or more precisely, I have seen a podcast app which fails to display the icon, which could be either the fault of the app or the podcast feed).

**Comment by bottiger** [comment]
@willemw12 I have made a (very) crude implementation of a list in the upcoming 0.88 release. I will continuously give it some love and make it nice and pretty but I would really like some feedback on which direction you think it should go.

Please don't be afraid to be harsh :)

**Comment by smarquespt** [comment]
@bottiger 

For this one I suggest to use podcast image on left side of the title

**Comment by willemw12** [comment]
Yes, the list view definitely needs an image column on the left. See http://developer.android.com/design/style/metrics-grids.html for info about icon size and row height, etc.

The large font (on the Subscriptions and Discover tabs) is OK or can be a little bit smaller as it is now on the Playlist tab.

**Comment by bottiger** [comment]
@willemw12 RIght. I'll make sure to update the layout for 0.96

**Comment by willemw12** [comment]
The new subscription list view reverts to the old single column icon view. This only seems to happen when the screen rotation option is enabled.

**Comment by bottiger** [comment]
@willemw12 

I am playing around with a list view which looks somewhat like this. Any kind of feedback is more than welcome. Especially because I do not use it myself, so it's hard for me to give it the love it needs.

![screenshot_2015-05-18-08-26-10](https://cloud.githubusercontent.com/assets/489129/7675372/1aa5321a-fd38-11e4-91fb-376d6de0139a.png)

**Comment by willemw12** [comment]
Looks great. Maybe add the published date of the latest episode (18-May, May-18) at the end of the 'new episodes' line?

(Do you like the rounded images? I've seen rounded logo/icons and rounded single characters.)

Not related to this issue:
In the single subscription list and the playlist, maybe add the published date (18-May, May-18) and the size (20 MB) to each episode?

**Comment by bottiger** [comment]
@willemw12 

> Looks great. Maybe add the published date of the latest episode (18-May, May-18) at the end of the 'new episodes' line?

Sure, I might actually replace it "5 new episodes" with the date for the latest episode for now since I do not have the logic in place for outputting the number of new episodes.

> (Do you like the rounded images? I've seen rounded logo/icons and rounded single characters.)

I like the rounded images very much.

> In the single subscription list and the playlist, maybe add the published date (18-May, May-18) and the size (20 MB) to each episode?

All that information will be there. However, I really need to finalize on a layout. At the moment I am spending all of my time on rewriting the playlist layout again and again. I want to get it done, right and out of the way so I can focus on other things. I would like to make use of all the podcast images in the design, but it is difficult to do it without the app turning into a rainbow :) 

However, I will add these basic labels when it's done.
