### ISSUE TITLE
Cannot disable notification

### ISSUE THREAD

**Issue by willemw12** [bottiger/SoundWaves#46]
The notification (player) is always there when playing, even when notifications are disabled in the settings. Restarting the app does not help.

**Comment by bottiger** [comment]
It looks like I'm a bit out of the loop. In the old days (I think) it was possible to have a Service running (playing) media without a notification. However, as far as I can see this has not been possible since 4.3.

It's probably for the best, but if you do not like the notification I'm afraid you are out of luck :(
I think I'll remove the settings instead, unless you have a solution

**Comment by willemw12** [comment]
I always have notifications on. Removing the settings is OK, I think, but unusual. Most apps do have this option. Maybe you need to call newer APIs for a proper fix?

In "App notifications" in the Android settings you can disable notifications of a (spammy) app.

**Comment by bottiger** [comment]
Not this type of notification.

In order for the podcasts to play when a user navigates away from the app is to have a service running - playing the episode. However, Android will kill this service after some time. On my old phone it took around 20 minutes - and the playback will just stop.

You can prevent this by running the service in the foreground. This is specifically designed towards playing music in the background when the user is away from the main app. 

However, a lot of developers misused this feature and just starting a permanent foreground service because it was convenient to have it running all the time. So since Android 4.3 it seem like Google have made this notification mandatory whenever you have a service running in the foreground.

You can not disable it (not even from the Android settings) and you cannot remove it when it's there. 

I guess it's a bit unfortunate in this case, but I guess it's better than having a lot of random services running all the time - because developers are lazy :)

**Comment by willemw12** [comment]
Yes you can disable it. I just tried it. And it makes sense you can do this:

> So since Android 4.3 it seem like Google have made this notification mandatory whenever you have a service running in the foreground.

Reason for Google to do this is to find, for example, spammy notifications or always running apps. And to easily force disabling these notifications or lowering the notification priority from the Android settings.

My point was: it's OK to use this (forceful) method for SoundWaves, however, usually apps have an option in their settings to disable notifications.

**Comment by bottiger** [comment]
Let it be clear - if I can disable it I will have that option available (somewhere). However, I am very confused about this. I can not get rid of the Notification on my devices, and [the documentation is very clear about it:](http://developer.android.com/guide/components/services.html#Foreground)

>A foreground service is a service that's considered to be something the user is actively aware of and thus not a candidate for the system to kill when low on memory. A foreground service must provide a notification for the status bar, which is placed under the "Ongoing" heading, which means that the notification cannot be dismissed unless the service is either stopped or removed from the foreground.
>
>For example, a music player that plays music from a service should be set to run in the foreground, because the user is explicitly aware of its operation. The notification in the status bar might indicate the current song and allow the user to launch an activity to interact with the music player.
>
>To request that your service run in the foreground, call startForeground(). This method takes two parameters: an integer that uniquely identifies the notification and the Notification for the status bar. 

How did you do it? Did I miss something?

**Comment by willemw12** [comment]
> How did you do it? Did I miss something?

Long press on the notification, then press the "i" on the right. Or from the Android (system) menu: Sound & notification --> App notifications. Here you can block or raise the priority of the app's notifications. It's a new feature, since Android 5, I believe. I am running 5.0.2.

What I think is not correct is that you can swipe away the notification. All other player or server related notifications I have seen, you cannot swipe away. You close or hide the player or server (connection/session) by tapping a button on the notification.

**Comment by bottiger** [comment]
@willemw12 
I am beginning to understand now. When I pause the PlayerService is sent to the background.
There may also be situations where I can not attach the server to the foreground. I have not looked into this, but maybe only one service can be in the foreground at once.

In any case: The notification can be removed when the service is not running in the foreground and it may be the case that this is the case sometimes.
It also fits with my personal experience that sometimes the player will stop randomly after a period of playback.

**Comment by bottiger** [comment]
Fixed in master branch
