### ISSUE TITLE
Crash when clicking subscription

### ISSUE THREAD

**Issue by smarquespt** [bottiger/SoundWaves#6]
How to reproduce:

1. Search for "Outra Coisa" podcast from gpodder or Import from Opml
2. Subscribe
3. Click podcast image

Observed:

Sorry, soundwaves has crashed (or something like it)

Expected:

Podcast populated

I´m on Android 4.1 with f-droid build 0.7.2.

What more can I do to narrow this? I´ve already enabled send crash reports.

**Comment by bottiger** [comment]
Thank you for letting me know.

Let me try to reproduce it first, I will give it a shot tonight. I may be easy to reproduce since I have had a fare share of issues with various versions of 4.1.

That said, if I am not able to reproduce it, the best solution would be to wait a little bit. The crash reporting is still not working in the f-droid version, but it will be fixed in the next version (0.74).
If you can reproduce this crash in 0.74 (and you probably can) I should get a crash report which should be very helpful in locating and fixing the problem.

I expect to push 0.74 out this weekend and should be on f-droid in a few days from there.

**Comment by smarquespt** [comment]
> I may be easy to reproduce since I have had a fare share of issues with various versions of 4.1.

Sorry my bad. I´m on 4.3

**Comment by bottiger** [comment]
Ok, good to know :)

**Comment by smarquespt** [comment]
Fixed in 0.74

**Comment by bottiger** [comment]
Good to hear :)
